"""Render `docs/data-catalogue.md` from the registry (never hand-edited).

Three tables -- raw datasets, produced datasets, scripts -- all derived from the script headers plus
`raw_sources.toml`. Rows are sorted by (stage, name) for datasets and (highest output stage, path) for
scripts, so diffs stay small and reruns are byte-identical.

Notes rule: a script's `Notes:` header text is printed verbatim (continuation lines already joined by the
header parser) as a bullet "- <script>.py: <text>". Notes of scripts that write a raw dataset (the
fetchers) go under the raw table; notes of every other script go under the produced table. This is also
where a raw directory path's file-name pattern stays visible.
"""

from __future__ import annotations

from collections.abc import Iterable

from eupy.registry.model import Dataset, Registry, Script

BANNER = (
    "<!-- GENERATED — do not edit. Regenerate with `uv run python -m eupy.registry catalogue`. -->\n\n"
    "# Data catalogue\n\n"
    "> **GENERATED — do not edit.** Generated by `python -m eupy.registry catalogue` from the "
    "`Inputs` / `Outputs` / `Final` / `Impure` block in each script's module docstring (plus "
    "`src/eupy/registry/raw_sources.toml` for manual raw data). Stage = max(input stages) + 1; raw = stage 0. "
    "Stage numbers are display-only and may shift — refer to datasets by name. "
    "Lineage: [data-graph.md](data-graph.md).\n"
)
DASH = "—"


def _cell(text: str) -> str:
    """Escape a value for a Markdown table cell."""
    return text.replace("|", "\\|")


def _code(items: Iterable[str]) -> str:
    return ", ".join(f"`{i}`" for i in items)


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return lines


def _file(script: Script) -> str:
    return script.path.rsplit("/", 1)[-1]


def _produced_by(reg: Registry, ds: Dataset) -> str:
    if ds.producer is None:
        return f"external: {ds.origin}"
    return f"`{_file(reg.scripts[ds.producer])}`"


def _script_inputs(script: Script, *, with_sources: bool) -> str:
    """Dataset inputs plus free-text sources."""
    parts = [f"`{i}`" for i in script.inputs]
    if with_sources:
        parts += list(script.sources)
    return ", ".join(parts) or "none"


def _notes(scripts: Iterable[Script]) -> list[str]:
    return [f"- `{_file(s)}`: {s.notes}" for s in sorted(scripts, key=lambda s: s.path) if s.notes]


def _section(title: str, table: list[str], notes: list[str]) -> list[str]:
    out = [f"## {title}", "", *table]
    if notes:
        out += ["", "Notes:", "", *notes]
    return [*out, ""]


def render_catalogue(reg: Registry) -> str:
    """Return the full Markdown text of the catalogue for `reg`."""
    datasets = sorted(reg.datasets.values(), key=lambda d: (d.stage, d.name))
    raw = [d for d in datasets if d.raw]
    produced = [d for d in datasets if not d.raw]
    raw_writers = {d.producer for d in raw if d.producer}

    raw_rows = [
        [
            f"`{d.name}`",
            f"`{d.path}`",
            _produced_by(reg, d),
            _code(_file(reg.scripts[c]) for c in d.consumers) or DASH,
            d.refresh or DASH,
        ]
        for d in raw
    ]
    prod_rows = [
        [
            f"`{d.name}`",
            f"{d.stage:02d}",
            f"`{d.path}`",
            _produced_by(reg, d),
            _script_inputs(reg.scripts[d.producer], with_sources=False) if d.producer else DASH,
            str(d.final).lower(),
            f"`data/stage_99/{d.path.rsplit('/', 1)[-1]}`" if d.final else DASH,
        ]
        for d in produced
    ]
    ordered = sorted(reg.scripts.values(), key=lambda s: (max((reg.stage(o) for o in s.outputs), default=0), s.path))
    script_rows = [
        [
            f"`{s.path}`",
            _script_inputs(s, with_sources=True),
            _code(s.outputs) or "none",
            str(s.final).lower(),
            str(s.impure).lower(),
        ]
        for s in ordered
    ]
    lines = [BANNER]
    lines += _section(
        "Raw datasets (`data/raw_data/` untracked; `data/curated/` tracked)",
        _table(["Dataset", "Path", "Produced by", "Consumed by", "Refresh"], raw_rows),
        _notes(reg.scripts[n] for n in sorted(raw_writers)),
    )
    lines += _section(
        "Produced datasets (`data/stage_XX/`)",
        _table(["Dataset", "Stage", "Path", "Produced by", "Inputs", "Final", "`stage_99` symlink"], prod_rows),
        _notes(s for s in reg.scripts.values() if s.name not in raw_writers),
    )
    lines += _section(
        "Scripts",
        _table(["Script", "Inputs", "Outputs", "Final", "Impure"], script_rows),
        [],
    )
    return "\n".join(lines).rstrip("\n") + "\n"
