"""Render `docs/data-graph.md` (a Mermaid `flowchart LR`) from the registry (never hand-edited).

Nodes: external sources (stadium), scripts (rectangle), datasets (cylinder). Ids are `x_<source>`,
`s_<script>`, `d_<dataset>` with the full name sanitized to `[A-Za-z0-9_]`; two names that sanitize to the
same id raise `GraphError`. Edges are exactly `Registry.edges()`.

Pipelines (optional `pipelines` argument, from `pipelines.toml`): one `subgraph p_<pipeline>["<pipeline>"]` per
pipeline, sorted by name, holding that pipeline's script nodes. Sources and datasets stay outside. Subgraph
ids are not nodes (they get no class and are outside the coverage check). Without `pipelines` the graph is flat.

Colors: one hue per stage from the fixed `PALETTE` (index = stage; `GraphError` when a stage exceeds it).
A dataset takes its stage hue, a `final` dataset the same hue with a thick border and a `★` label suffix;
a script has a neutral fill with the stroke of its highest output stage; sources are gray. Every node gets
exactly one class and every class member is a declared node -- checked here, raising `GraphError`.
Output is sorted and timestamp-free, so reruns are byte-identical.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from eupy.registry.dvc_gen import Pipeline
from eupy.registry.model import Registry

# (fill, stroke, text) per stage; stage N uses PALETTE[N].
PALETTE: tuple[tuple[str, str, str], ...] = (
    ("#fde9d9", "#c97f3a", "#4a2c0a"),  # 0 amber (raw)
    ("#dcecdc", "#5a9c5a", "#1e3a1e"),  # 1 green
    ("#dbe9f6", "#5b84a3", "#1a2b3c"),  # 2 blue
    ("#ece0f5", "#8a62a8", "#2f1a40"),  # 3 purple
    ("#f9dede", "#c05a5a", "#4a1414"),  # 4 red
    ("#fbf3cc", "#b39b2a", "#3f3505"),  # 5 yellow
    ("#d8f0ee", "#3f9b93", "#0c3733"),  # 6 teal
    ("#fbe0ee", "#c2579a", "#4a1234"),  # 7 pink
)
SOURCE_STYLE = "fill:#e8e8e8,stroke:#888888,color:#333333"
SCRIPT_FILL, SCRIPT_TEXT = "#f7f7f7", "#222222"
THICK = "stroke-width:4px"

BANNER = (
    "<!-- GENERATED — do not edit. Regenerate with `uv run python -m eupy.registry graph`. -->\n\n"
    "# Data graph\n\n"
    "> **GENERATED — do not edit.** Generated by `python -m eupy.registry graph` from the script I/O headers "
    "(plus `src/eupy/registry/raw_sources.toml`). Shapes: stadium = external source, rectangle = script, "
    "cylinder = dataset (raw or produced). Colors: one hue per stage (datasets take their stage hue; scripts are "
    "neutral with a stroke in the hue of their highest output stage; external sources are gray). "
    "Boxes group scripts by pipeline (`pipelines.toml`). "
    "`★` + thick border = `final` dataset (exposed under `data/stage_99/`). "
    "Inventory: [data-catalogue.md](data-catalogue.md).\n"
)


class GraphError(Exception):
    """The registry cannot be drawn (id collision, exhausted palette, coverage violation)."""


def _ident(prefix: str, name: str) -> str:
    return f"{prefix}_{re.sub(r'[^A-Za-z0-9_]', '_', name)}"


def _esc(text: str) -> str:
    """Escape characters Mermaid would read as entities or HTML inside a quoted label."""
    escaped = text.replace("#", "#35;").replace('"', "#quot;").replace("<", "#lt;").replace(">", "#gt;")
    return escaped.replace("&", "#amp;")


def _q(text: str) -> str:
    """Quote a Mermaid label."""
    return '"' + _esc(text) + '"'


def _hue(stage: int) -> tuple[str, str, str]:
    if stage >= len(PALETTE):
        raise GraphError(f"stage {stage} has no color: PALETTE has {len(PALETTE)} hues; extend it")
    return PALETTE[stage]


def _mermaid_ids(reg: Registry) -> dict[str, str]:
    """Registry node id -> Mermaid id; raises `GraphError` when two nodes sanitize to the same id."""
    ids = {f"source:{label}": _ident("x", label) for label in reg.sources}
    ids |= {f"script:{name}": _ident("s", name) for name in reg.scripts}
    ids |= {f"dataset:{name}": _ident("d", name) for name in reg.datasets}
    seen: dict[str, str] = {}
    for node, mid in ids.items():
        if mid in seen:
            raise GraphError(f"id collision: {seen[mid]} and {node} both sanitize to {mid}")
        seen[mid] = node
    return ids


def _declarations(reg: Registry, ids: dict[str, str]) -> tuple[dict[str, tuple[str, str]], dict[str, str]]:
    """Per node `(declaration, class)` in output order, plus the style of every class used."""
    decl: dict[str, tuple[str, str]] = {}
    classes: dict[str, str] = {"source": SOURCE_STYLE}
    for label in sorted(reg.sources):
        node = f"source:{label}"
        decl[node] = (f"{ids[node]}([{_q(label)}])", "source")
    for name, script in sorted(reg.scripts.items()):
        node = f"script:{name}"
        stage = max((reg.stage(o) for o in script.outputs), default=0)
        cls = f"script_stage{stage}"
        classes[cls] = f"fill:{SCRIPT_FILL},stroke:{_hue(stage)[1]},color:{SCRIPT_TEXT}"
        decl[node] = (f"{ids[node]}[{_q(name)}]", cls)
    for name, ds in sorted(reg.datasets.items(), key=lambda kv: (kv[1].stage, kv[0])):
        node = f"dataset:{name}"
        fill, stroke, text = _hue(ds.stage)
        cls = f"stage{ds.stage}_final" if ds.final else f"stage{ds.stage}"
        classes[cls] = f"fill:{fill},stroke:{stroke},color:{text}" + (f",{THICK}" if ds.final else "")
        label = f"{_esc(name)}{' ★' if ds.final else ''}<br/>(stage {ds.stage})"
        decl[node] = (f'{ids[node]}[("{label}")]', cls)
    return decl, classes


@dataclass(frozen=True)
class GraphModel:
    """The drawable graph shared by every renderer (Mermaid markdown, HTML map).

    `ids`: registry node id (`source:`/`script:`/`dataset:` prefix) -> graph id. `decl`: node -> `(Mermaid
    declaration, class)` in output order. `classes`: class -> Mermaid style string. `edges`: sorted
    `(from, to)` registry node pairs -- `Registry.edges()`.
    """

    ids: dict[str, str]
    decl: dict[str, tuple[str, str]]
    classes: dict[str, str]
    edges: tuple[tuple[str, str], ...]


def build_model(reg: Registry) -> GraphModel:
    """Nodes, ids, classes and edges of `reg`, coverage-checked; raises `GraphError` on an undrawable registry."""
    ids = _mermaid_ids(reg)
    decl, classes = _declarations(reg, ids)

    edges = set(reg.edges())

    members: dict[str, list[str]] = {}
    for node, (_, cls) in decl.items():
        members.setdefault(cls, []).append(ids[node])
    _check_coverage(set(ids.values()), members, set(classes))
    return GraphModel(ids, decl, classes, tuple(sorted(edges)))


def render_graph(reg: Registry, pipelines: dict[str, Pipeline] | None = None) -> str:
    """Return the full Markdown text of the graph for `reg`; raises `GraphError` on an undrawable registry.

    With `pipelines`, script nodes are grouped into one subgraph per pipeline (sorted by name).
    """
    model = build_model(reg)
    ids, decl, classes = model.ids, model.decl, model.classes
    arrows = sorted(f"{ids[a]} --> {ids[b]}" for a, b in model.edges)
    members: dict[str, list[str]] = {}
    for node, (_, cls) in decl.items():
        members.setdefault(cls, []).append(ids[node])

    lines = [BANNER, "```mermaid", "flowchart LR"]
    grouped = {f"script:{s}" for p in (pipelines or {}).values() for s in p.scripts if s in reg.scripts}
    for title, kind in (("external sources", "source"), ("scripts", "script"), ("datasets", "dataset")):
        lines.append(f"    %% {title}")
        lines += [f"    {d}" for node, (d, _) in decl.items() if node.startswith(f"{kind}:") and node not in grouped]
        if kind == "script":
            for pname, pipe in sorted((pipelines or {}).items()):
                lines.append(f"    subgraph {_ident('p', pname)}[{_q(pname)}]")
                lines += [f"        {decl[f'script:{s}'][0]}" for s in sorted(pipe.scripts) if s in reg.scripts]
                lines.append("    end")
        lines.append("")
    lines += ["    %% edges", *(f"    {a}" for a in arrows), "", "    %% colors by stage"]
    lines += [f"    classDef {c} {classes[c]}" for c in sorted(classes)]
    lines += [f"    class {','.join(sorted(members[c]))} {c}" for c in sorted(members)]
    lines += ["```", ""]
    return "\n".join(lines)


def _check_coverage(declared: set[str], members: dict[str, list[str]], defined: set[str]) -> None:
    """Every declared node in exactly one class; every class member declared; every used class defined."""
    counts: dict[str, int] = {}
    for ids in members.values():
        for mid in ids:
            counts[mid] = counts.get(mid, 0) + 1
    problems = [f"node {m} has no class" for m in sorted(declared - counts.keys())]
    problems += [f"class member {m} is not a declared node" for m in sorted(counts.keys() - declared)]
    problems += [f"node {m} is in {n} classes" for m, n in sorted(counts.items()) if n > 1]
    problems += [f"class {c} is used but has no classDef" for c in sorted(set(members) - defined)]
    if problems:
        raise GraphError("; ".join(problems))
