"""Column explanations for the `Column Guide` sheet of the player master workbook.

One short explanation per source-dataset column, based on the fetch scripts and
SKILL.md files under `.claude/skills/*` plus standard basketball-analytics
definitions. Entries marked "(unverified)" could not be confirmed from those
sources. Keys are the column names exactly as they appear in each source CSV.
"""

from __future__ import annotations

DUNKEST = "Dunkest"
BN_ADVANCED = "BN Advanced"
BN_ONOFF = "BN On-Off"
FANTASY_PRICES = "Fantasy Prices"

UNDOCUMENTED = "(undocumented: new column, add to player_master_column_guide.py)"

_DUNKEST_GUIDE = {
    "id": "Dunkest player id",
    "gp": "Games played; master games_played (preferred source)",
    "first_name": "First name; master player_name = first + last",
    "last_name": "Last name (suffix like Iv/Jr included)",
    "team_id": "Dunkest team id",
    "team_code": "Dunkest short team code",
    "team_name": "Team name; master team_name (preferred source)",
    "position": "G/F/C; master position (fallback: BN Advanced, then Fantasy)",
    "position_id": "Position id: 1=Guard, 2=Forward, 3=Center",
    "cr": "Fantasy credit value (all 0 in current data)",
    "pdk": "Fantasy points per game",
    "min": "Minutes per game",
    "starter": "Games started",
    "pts": "Points per game",
    "ast": "Assists per game",
    "reb": "Rebounds per game",
    "stl": "Steals per game",
    "blk": "Blocks per game",
    "blka": "Own shots blocked by opponents per game",
    "fgm": "Field goals made per game",
    "fgm_tot": "Field goals made, season total",
    "fga": "Field goals attempted per game",
    "fga_tot": "Field goals attempted, season total",
    "tpm": "Three-pointers made per game",
    "tpm_tot": "Three-pointers made, season total",
    "tpa": "Three-pointers attempted per game",
    "tpa_tot": "Three-pointers attempted, season total",
    "ftm": "Free throws made per game",
    "ftm_tot": "Free throws made, season total",
    "fta": "Free throws attempted per game",
    "fta_tot": "Free throws attempted, season total",
    "oreb": "Offensive rebounds per game",
    "dreb": "Defensive rebounds per game",
    "tov": "Turnovers per game",
    "pf": "Personal fouls per game",
    "fouls_received": "Fouls drawn per game",
    "plus_minus": "Plus/minus per game (unverified)",
    "fgp": "Field goal percentage",
    "tpp": "Three-point percentage",
    "ftp": "Free throw percentage",
    "slug": "Dunkest URL slug of the player",
}

_BN_ADVANCED_GUIDE = {
    "season": "Season start year (2025 = 2025-26)",
    "league_id": "Basketnews league id (25 = EuroLeague)",
    "mode": "Row type: offensive or defensive stat set",
    "player_id": "Basketnews player id (master key column)",
    "player_name": "Full player name",
    "player_name_short": "Abbreviated player name",
    "team_id": "Basketnews team id",
    "team_name": "Team name",
    "team_short_name": "Team short name",
    "positions": "Eligible positions, e.g. SG,SF; master position fallback 1",
    "games_played": "Games played",
    "minutes_per_game": "Minutes per game (MM:SS)",
    "minutes_per_game_raw": "Minutes per game in seconds",
    "offensive_rating_lineup": "Team offensive rating with player on court (unverified)",
    "offensive_rating_ind": "Individual offensive rating, points per 100 possessions",
    "points": "Points scored per game",
    "3p_percentage": "Three-point percentage",
    "2p_percentage": "Two-point percentage",
    "ft_percentage": "Free throw percentage",
    "ts_percentage": "True shooting percentage",
    "3p_attempted": "Three-pointers attempted per game",
    "2p_attempted": "Two-pointers attempted per game",
    "ft_attempted": "Free throws attempted per game",
    "3p_attempted_rate": "Share of shots attempted from three",
    "created_points": "Points created by player's scoring and passing (unverified)",
    "assists": "Assists per game",
    "assist_percentage": "Share of teammate baskets assisted while on court",
    "turnovers": "Turnovers per game",
    "turnover_percentage": "Turnovers per 100 plays",
    "offensive_rebounds": "Offensive rebounds per game",
    "offensive_rebound_percentage": "Share of available offensive rebounds grabbed",
    "fouls_received": "Fouls drawn per game",
    "blocks_received": "Own shots blocked by opponents per game",
    "usage_percentage": "Share of team plays used while on court",
    "defensive_rating_lineup": "Team defensive rating with player on court (unverified)",
    "defensive_rating_ind": "Individual defensive rating, points allowed per 100 possessions",
    "stops": "Defensive stops (per game unverified)",
    "stop_percentage": "Share of opponent possessions ended in a stop (unverified)",
    "defensive_rebounds": "Defensive rebounds per game",
    "defensive_rebound_percentage": "Share of available defensive rebounds grabbed",
    "steals": "Steals per game",
    "steal_percentage": "Steals per 100 opponent possessions",
    "blocks": "Blocks per game",
    "block_percentage": "Share of opponent two-point attempts blocked",
    "foul_stops": "Stops from drawing/committing fouls (unverified)",
}

_BN_ONOFF_GUIDE = {
    "league": "League name",
    "league_id": "Basketnews league id (25 = EuroLeague)",
    "season": "Season start year (2025 = 2025-26)",
    "view": "Row type: total, offensive or defensive",
    "team_id": "Basketnews team id",
    "team_name": "Team name",
    "team_short_name": "Team short name",
    "player_id": "Basketnews player id",
    "player_name": "Full player name",
    "position": "Player position",
    "games_played": "Games played",
    "time_played_formatted": "Time on court (MM:SS)",
    "time_played": "Time on court in seconds",
    "offensive_rating_lineup": "Team offensive rating with player on court",
    "offensive_rating_lineup_diff": "Offensive rating difference, on vs off court (sign unverified)",
    "defensive_rating_lineup": "Team defensive rating with player on court",
    "defensive_rating_lineup_diff": "Defensive rating difference, on vs off court (sign unverified)",
    "net_rating_lineup": "Team net rating with player on court",
    "net_rating_lineup_diff": "Net rating difference, on vs off court (sign unverified)",
    "possessions_lineup": "Team possessions with player on court",
    "possession_percentage_lineup": "Share of team possessions with player on court",
    "points_lineup": "Team points scored with player on court",
    "points_opponent_lineup": "Opponent points with player on court",
    "net_points_lineup": "Point differential with player on court",
    "rebound_percentage_lineup": "Team rebound percentage with player on court",
    "rebound_percentage_lineup_diff": "Rebound % difference, on vs off court (sign unverified)",
    "offensive_rating_lineup_wo": "Team offensive rating without player (unverified)",
    "offensive_rebound_percentage_lineup": "Team offensive rebound % with player on court",
    "offensive_rebound_percentage_lineup_diff": "Off. rebound % difference, on vs off (sign unverified)",
    "2p_attempted_lineup": "Team two-pointers attempted with player on court",
    "2p_percentage_lineup": "Team two-point % with player on court",
    "2p_percentage_lineup_diff": "Two-point % difference, on vs off (sign unverified)",
    "3p_attempted_lineup": "Team three-pointers attempted with player on court",
    "3p_attempted_rate_lineup": "Team three-point attempt rate with player on court",
    "3p_attempted_rate_lineup_diff": "Three-point rate difference, on vs off (sign unverified)",
    "3p_percentage_lineup": "Team three-point % with player on court",
    "3p_percentage_lineup_diff": "Three-point % difference, on vs off (sign unverified)",
    "fouls_received_rate_lineup": "Team fouls-drawn rate with player on court (unverified)",
    "fouls_received_rate_lineup_diff": "Fouls-drawn rate difference, on vs off (unverified)",
    "assist_percentage_lineup": "Team assist % with player on court",
    "assist_percentage_lineup_diff": "Assist % difference, on vs off (sign unverified)",
    "turnover_percentage_lineup": "Team turnover % with player on court",
    "turnover_percentage_lineup_diff": "Turnover % difference, on vs off (sign unverified)",
    "defensive_rating_lineup_wo": "Team defensive rating without player (unverified)",
    "possession_percentage_opponent_lineup": "Opponent possession share with player on court (unverified)",
    "defensive_rebound_percentage_lineup": "Team defensive rebound % with player on court",
    "defensive_rebound_percentage_lineup_diff": "Def. rebound % difference, on vs off (sign unverified)",
    "2p_attempted_opponent_lineup": "Opponent two-pointers attempted with player on court",
    "2p_percentage_opponent_lineup": "Opponent two-point % with player on court",
    "2p_percentage_opponent_lineup_diff": "Opp. two-point % difference, on vs off (sign unverified)",
    "3p_attempted_opponent_lineup": "Opponent three-pointers attempted with player on court",
    "3p_attempted_rate_opponent_lineup": "Opponent three-point attempt rate with player on court",
    "3p_attempted_rate_opponent_lineup_diff": "Opp. three-point rate difference, on vs off (sign unverified)",
    "3p_percentage_opponent_lineup": "Opponent three-point % with player on court",
    "3p_percentage_opponent_lineup_diff": "Opp. three-point % difference, on vs off (sign unverified)",
    "fouls_rate_lineup": "Team fouls-committed rate with player on court (unverified)",
    "fouls_rate_lineup_diff": "Fouls rate difference, on vs off (unverified)",
    "assist_percentage_opponent_lineup": "Opponent assist % with player on court",
    "assist_percentage_opponent_lineup_diff": "Opp. assist % difference, on vs off (sign unverified)",
    "turnover_percentage_opponent_lineup": "Opponent turnover % with player on court",
    "turnover_percentage_opponent_lineup_diff": "Opp. turnover % difference, on vs off (sign unverified)",
}

_FANTASY_PRICES_GUIDE = {
    "rank": "Rank on the price page, by price descending",
    "name": "Player or head coach name",
    "club": "Club name (short form)",
    "position": "G/F/C, HC for coaches; master position fallback 2",
    "price": "EuroLeague Fantasy credit price",
    "role": "player or head_coach (derived from position)",
}

GUIDE: dict[str, dict[str, str]] = {
    DUNKEST: _DUNKEST_GUIDE,
    BN_ADVANCED: _BN_ADVANCED_GUIDE,
    BN_ONOFF: _BN_ONOFF_GUIDE,
    FANTASY_PRICES: _FANTASY_PRICES_GUIDE,
}
